M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu25.04.1} date 2026-02-21T14:51:13+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-21T14:51:13+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu25.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X5.3465Y-4.459
X6.3465Y-4.459
M30
